// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LowPolyiOS
{
	public partial class TriangulationView : UIView
	{
		public TriangulationView (IntPtr handle) : base (handle)
		{
		}
	}
}
